local addonName, addon = ...
addon = LibStub("AceAddon-3.0"):GetAddon(addonName)

addon.Patrons = {
    "Adam Van Hoosen",
    "Chaos",
    "Chris",
    "Cody",
    "David LaSelle",
    "Dejoblue ",
    "Evan Hardin",
    "Ines Tan",
    "JSON",
    "James Leadbetter-Brown",
    "Jason Harper",
    "Joe Romubio",
    "Joshua Hall",
    "Kai Olsen ",
    "Lucky Phil",
    "MangoSentinelEX",
    "Matthew Dine",
    "Michael and Jon Baglivo-Zarin",
    "Noty",
    "Nuke Prin",
    "Oisín McColgan",
    "PENT ",
    "Pentasphere ",
    "Peter Muzi",
    "Peter Portela",
    "Randy Ramirez",
    "Ray Patronson",
    "Somarlane ",
    "Tou",
    "marilyn lewis",
    "toast042"
}