local addonName, addon = ...
addon = LibStub("AceAddon-3.0"):GetAddon(addonName)

addon.Patrons = {
    "Adam Van Hoosen",
    "Chaos",
    "Chris",
    "Chris Archibald",
    "Chris Ellis",
    "Cody",
    "David LaSelle",
    "Dejablue",
    "Evan Hardin",
    "Ines Tan",
    "JSON",
    "James Leadbetter-Brown",
    "Jason Harper",
    "Joe Romubio",
    "Joshua Hall",
    "Juliette 🤍",
    "Kai Olsen ",
    "Kevil",
    "Kroome K.",
    "Lucky Phil",
    "MangoSentinelEX",
    "Matthew Dine",
    "Martin van Vuuren",
    "Michael and Jon Baglivo-Zarin",
    "Nicolette Korpolinski",
    "Noty",
    "Nuke Prin",
    "Oisín McColgan",
    "Pentasphere ",
    "Peter Muzi",
    "Peter Portela",
    "Randy Ramirez",
    "Ray Patronson",
    "Somarlane ",
    "Stonie",
    "Tou",
    "Vinicius Alencar",
    "ZaffronStaghelm",
    "marilyn lewis",
    "pent",
    "sebastian volf",
    "toast042",
    "vulpes lotor",

}